myproject/urls.py
from django.contrib import admin
from django.urls import path, re_path
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

from boards import views

urlpatterns = [
    path('', views.BoardListView.as_view(), name='home'),
    # path('', views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('test/', views.test, name='test'),
    re_path(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    re_path(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    path('admin/', admin.site.urls),

    re_path(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ), name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='my_account'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
]

boards/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.utils.text import Truncator
from markdown import markdown

# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name = 'topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name = 'topics', on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name = 'posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name = 'posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, related_name = '+', null=True, on_delete=models.CASCADE)

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

boards/forms.py
from django import forms
from .models import Topic
from .models import Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
        attrs = {'rows':5, 'placeholder': '请填上你想到的！'}
    ), max_length=4000, 
    help_text="The max length of the text is 4000.")

    class Meta:
        model = Topic
        fields = ['subject', 'message']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Django Boards{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        {% block stylesheet %}{% endblock %}
    </head>
    <body>
        {% block body %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>

                <!--Add User Information on the Top-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainMenu">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href="{% url 'my_account' %}">我的账户</a>
                                <a class="dropdown-item" href="#">修改密码</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">注销</a>
                              </div>
                        </li>
                    </ul>
                    {% else %}
                        <form class="form-inline ml-auto">
                            <a href="{% url 'login' %}" class="btn btn-outline-secondary">登录</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">注册</a>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container">
            <ol class="breadcrumb my-4">
                {% block breadcrumb %}
                {% endblock %}
            </ol>
            {% block content %}
            {% endblock %}
        </div>
        {% endblock body %}

        <script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block javascript %}{% endblock %}
    </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{% comment %} {% block stylesheet %}
  <link ref="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %} {% endcomment %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">保存更改</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class='breadcrumb-item active'>Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td class="align-middle">
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">{{ board.get_posts_count }}</td>
          <td class="align-middle">{{ board.topics.count }}</td>
          <td class="align-middle">
            {% with post=board.get_last_post %}
              {% if post %}
                <small>
                  <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
                    By {{ post.created_by.username }} at {{ post.created_at }}
                  </a>
                </small>
              {% else %}
                <small class="text-muted">
                  <em>No posts yet.</em>
                </small>
              {% endif %}
            {% endwith %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}


{% comment %} <td class="align-middle">{{ board.get_posts_count }}</td>
<td class="align-middle">{{ board.topics.count }}</td>
<td class="align-middle">a
  {% with post=board.get_last_post %}
    {% if post %}
      <small>
        <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
          By {{ post.created_by.username }} at {{ post.created_at }}
        </a>
      </small>
    {% else %}
      <small class="text-muted">
        <em>No posts yet.</em>
      </small>
    {% endif %}
  {% endwith %} {% endcomment %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}登录Django Board{% endblock %}
{% block content %}
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">登录</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">登录</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            还没有账号？ <a href="{% url 'signup' %}">注册</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="{% url 'password_reset' %}" class="text-muted">忘记密码?</a>
          </small>
        </div>
      </div>
    </div>
{% endblock %}

templates/my_account.html
{% extends 'base.html' %}

{% block title %}我的账户{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">我的账户</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">保存修改</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
    <!--Traditional Form Method-->
    <!--form method = "POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_subject">Subject</label>
            <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <div class="form-group">
            <label for="id_message">Message</label>
            <textarea class="form-control" id="id_message" name="message" row="5"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form-->

    <!--With Form API-->
    <form method="post" novalidate>
        {% csrf_token %}

        {% include 'includes/form.html' %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <button type="submit" class="btn btn-success">Post</button>
        <a href="{% url 'board_topics' board.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
    </form>

{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}修改密码{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">修改密码</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">修改密码</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}重置密码{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">重置密码</h3>
          <!--p>Enter your email address and we will send you a link to reset your password.</p-->
          <p>请输入邮箱地址，我们会将连接发送到您的邮箱。</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">发送密码重置邮件</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    为用户{{ form.user.username }}修改密码
  {% else %}
    重置您的密码
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">为用户@{{ form.user.username }}修改密码</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">修改密码</button>
            </form>
          {% else %}
            <h3 class="card-title">重置您的密码</h3>
            <div class="alert alert-danger" role="alert">
              <!--It looks like you clicked on an invalid password reset link. Please try again.-->
              似乎您点击了一个无效的密码重置连接，请重试！
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">请求重新发送密码重置连接</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}重置密码{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">重置密码</h3>
          <!--p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p-->
          <p>请检查你的邮箱连接，从而进行密码重置。如果一直未收到邮件，请检查垃圾邮件。</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">返回登录</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}注册账户{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">注册</h3>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% comment %} {{ form.as_p }} {% endcomment %}
                        {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-primary">注册</button>
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                    已经有账户了？<a href="{% url 'login' %}">登录</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

    <div class="mb-4">
        <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
    </div>

    {% for post in posts %}
        <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
        {% if forloop.first %}
            <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
        {% endif %}
        <div class="card-body p-3">
            <div class="row">
                <div class="col-2">
                    <img src="{% static 'img/profile.png' %}" alt="{{ post.created_by.username }}" class="w-100">
                    <small>Posted By: {{ post.created_by.username }}</small>
                </div>
                <div class="col-10">
                    <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at|naturaltime }}</small>
                    </div>
                    </div>
                    {{ post.get_message_as_markdown }}
                    {% if post.created_by == user %}
                    <div class="mt-3">
                        <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </div>
    {% endfor %}

    {% include 'includes/pagination.html' %}

{% endblock %}